version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: attendance_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employees
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: attendance_backend
    restart: always
    depends_on:
      - postgres
    environment:
      PORT: 5001
      DB_USER: postgres
      DB_HOST: postgres
      DB_DATABASE: employees
      DB_PASSWORD: postgres
      DB_PORT: 5432
      JWT_SECRET: your_secret_here
    ports:
      - "5001:5001"
